# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

stages:
- stage : GenerateArtefact
  jobs:
    - job: Artefact
      steps:
      - task: CopyFiles@2
        inputs:
          SourceFolder: 'arm/'
          Contents: '**'
          TargetFolder: '$(Build.ArtifactStagingDirectory)'
      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: '$(Build.ArtifactStagingDirectory)'
          ArtifactName: 'drop'
          publishLocation: 'Container'
        
      
- stage : InfrastructureDeployment
  pool:
   vmImage: 'ubuntu-latest' 
  jobs: 
  - job: Infrasturcture
    steps:
    - task: DownloadPipelineArtifact@2
      inputs:
        buildType: 'current'
        artifactName: 'drop'
        targetPath: '$(Build.ArtifactStagingDirectory)'   

    
    - task: AzureResourceManagerTemplateDeployment@3
      inputs:
        deploymentScope: 'Resource Group'
        azureResourceManagerConnection: 'AI-BoldPlay Service Connection'
        subscriptionId: '9ae9cf58-0498-42ff-8666-95badd20b8cd'
        action: 'Create Or Update Resource Group'
        resourceGroupName: 'AZRG-USE2-CON-030009-NPD'
        location: 'EAST US 2'
        templateLocation: 'Linked artifact'
        csmFile: '/home/vsts/work/1/a/ACRAKS.json'
        csmParametersFile: '/home/vsts/work/1/a/ACRAKSParameter.json'
        deploymentMode: 'Incremental'
        deploymentName: 'acrDeployement'
        deploymentOutputs: 'acrName'
                
    - task: PowerShell@2
      inputs:
            targetType: 'inline'
            script: |
              # Write your PowerShell commands here.              
              Write-Host "$(acrName)"
    
            
           
    
      


    

 
# - stage : CodeDeployment
#   dependsOn: InfrastructureDeployment 
#   pool:
#    vmImage: 'ubuntu-latest' 
#   jobs:
#     - job: CodeDeployment